#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:

sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOF
EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    daemon
    maxconn 2048

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms
    maxconn 2000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 98.81.157.44:80 check
    server web-02 34.224.212.77:80 check
EOL

# Enable and start HAProxy
sudo systemctl enable haproxy
sudo systemctl restart haproxy
EOF
